SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2014
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
    AND ESTCIV IS NOT NULL AND IDADE IS NOT NULL AND TIPOBITO IS NOT NULL AND ESC2010 IS NOT NULL AND CIRCOBITO IS NOT NULL
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2015
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2016
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2017
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2018
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2019
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2020
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2021
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2022
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
UNION ALL
SELECT
    * EXCEPT(IDADE),
    CAST(SUBSTR(CAST(IDADE AS STRING), 2) AS INT64) AS IDADE
FROM
    t1engenhariadados.Grupo_3_6_ProjetoFinal.SIM_2023
WHERE
    TIPOBITO = 2 AND CIRCOBITO = 2
